site_name: NOMAD Onboarding Workshop
site_description: |
  Temporary repo to produce the NOMAD onboarding workshop materials.
site_author: The FAIRmat Area F
repo_url: https://github.com/siamakn/temp-nomad-onboarding-workshop
edit_uri: ""

nav:
  - Home: index.md
  - Creating workshop materials:
    - Creating_Workshop_Materials/creating_workshop_materials.md
    - Creating_Workshop_Materials/git_collaboration_training_materials.md
  - RDM with NOMAD:
    - Introduction: Module 1/1_RDM_with_NOMAD.md
    - NOMAD data model: Module 1/1_RDM_with_NOMAD2.md
    - Levels of NOMAD users: Module 1/1_RDM_with_NOMAD3.md
    - Getting support: Module 1/1_RDM_with_NOMAD4.md
  - First touches with NOMAD:
    - Creating a user account: Module 2/2- First touches into NOMAD/2_0_Accessing NOMAD.md
    - The NOMAD graphical user interface (GUI): Module 1/1_RDM_with_NOMAD5.md
    - Uploading and pulishing data: Module 1/1_RDM_with_NOMAD6.md
    - Sharing and collaboration: Module 1/1_RDM_with_NOMAD7.md
    - Exploring data: Module 1/1_RDM_with_NOMAD8.md
  - Using NOMAD as an ELN:
    - Overview:
      - Introduction: Module 3/5_ELN using built-in schema/5_0_Overview.md
      - Planning your experiment: Module 3/5_ELN using built-in schema/5_01_Overview_plan.md
      - Documenting your plans: Module 3/5_ELN using built-in schema/5_02_Overview_document.md
      - Managing your experiments: Module 3/5_ELN using built-in schema/5_03_Overview_manage.md
      - Sharing your progress: Module 3/5_ELN using built-in schema/5_04_Overview_share.md
    - Getting Started: Module 3/5_ELN using built-in schema/5A_0_Getting_started.md
    - Creating Entities:
      - Create the entities of your experiments: Module 3/5_ELN using built-in schema/5B_0_Creating_entities.md
      - Substances: Module 3/5_ELN using built-in schema/5B_1_Substance_entities.md
      - Samples: Module 3/5_ELN using built-in schema/5B_2_Sample_entities.md
      - Instruments: Module 3/5_ELN using built-in schema/5B_3_Instrument_entities.md
    - Creating Activities: 
      - Create the activities of your experiments: Module 3/5_ELN using built-in schema/5C_0_Creating_activities.md
      - Processing: Module 3/5_ELN using built-in schema/5C_1_Materials_processing_activitiy.md
      - Measurements: Module 3/5_ELN using built-in schema/5C_2_Measurement_activity.md
    - Managing Experiments: 
      - Introduction: Module 3/5_ELN using built-in schema/5D_0_Managing_experiments.md
      - Organizing your upload: Module 3/5_ELN using built-in schema/5D_1_Organizing_your_upload.md
      - Recording your experiments: Module 3/5_ELN using built-in schema/5D_2_experiments_ELN.md
      - Sharing and Collaboration: Module 3/5_ELN using built-in schema/5E_0_sharing_ELN.md
  - Using NOMAD's API:
    - Overview: Module4/M4_0_overview.md
    - Getting Started:
      - Programming Environments: Module4/M4_1_getting_started/M4_1_0_getting_started.md
      - Local Installation: Module4/M4_1_getting_started/M4_1_1_preparing_local.md
      - Cloud-based (NORTH): Module4/M4_1_getting_started/M4_1_2_preparing_north.md
    - API Basics: Module4/M4_2_api_basics/M4_2_1_api_basics.md
    - A Simple API Call Explained: Module4/M4_3_nomad_example1/M4_3_1_rest_api_nomad_example.md
    - Leveraging Pagination: Module4/M4_3_nomad_example1/M4_3_2_rest_api_nomad_example.md

plugins:
 - search
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/fairmat-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  custom_dir: docs/theme
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://www.fairmat-nfdi.eu/fairmat/
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
#  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
