site_name: NOMAD Onboarding Workshop
site_description: |
  Temporary repo to produce the NOMAD onboarding workshop materials.
site_author: The FAIRmat Area F
repo_url: https://github.com/siamakn/temp-nomad-onboarding-workshop
edit_uri: ""

nav:
  - Home: index.md
  - Creating workshop materials:
    - Creating_Workshop_Materials/creating_workshop_materials.md
    - Creating_Workshop_Materials/git_collaboration_training_materials.md
  - Section1: Section1/Section1_mdfile.md
  - Section2:
    - Section2/Section2_mdfile.md
    - Section2_SubSection1: Section2/Section2_SubSection1/Section2_SubSection1_mdfile.md
    - Section2_SubSection2: Section2/Section2_SubSection2/Section2_SubSection2_mdfile.md
  - Using NOMAD as an ELN:
    - Overview: Module 3/5_0_Overview.md
    - Getting Started: Module 3/5A_0_Getting_started.md
    - Creating Entities: Module 3/5B_0_Creating_entities.md
    - Creating Activities: Module 3/5C_0_Creating_activities.md
    - Managing Experiments: Module 3/5D_0_Managing_experiments.md
    - Sharing and Collaboration: Module 3/5E_0_sharing_ELN.md
  - Using NOMAD's API:
    - Overview: Module4/M4_0_overview.md
    - Getting Started:
      - Programming Environments: Module4/M4_1_getting_started/M4_1_0_getting_started.md
      - Local Installation: Module4/M4_1_getting_started/M4_1_1_preparing_local.md
      - Cloud-based (NORTH): Module4/M4_1_getting_started/M4_1_2_preparing_north.md
    - API Basics: Module4/M4_2_api_basics/M4_2_1_api_basics.md
    - A Simple API Call Explained: Module4/M4_3_nomad_example1/M4_3_1_rest_api_nomad_example.md


plugins:
 - search
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/fairmat-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  custom_dir: docs/theme
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://www.fairmat-nfdi.eu/fairmat/
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js